const productsData = [
  {
    id: 1,
    title: "iPhone 14 Pro Max",
    price: 20400,
    discount: 3.3,
    prevPrice: 22000,
    imageUrl: "./images/alejandro-escamilla-tAKXap853rY-unsplash.jpg",
    category: "Electronics",
    stars: 4.3,
  },
  {
    id: 2,
    title: "Samsung Galaxy S22",
    price: 18000,
    discount: 5.0,
    prevPrice: 19000,
    imageUrl: "./images/yura-fresh-n31x0hhnzOs-unsplash.jpg",
    category: "Electronics",
    stars: 3.8,
  },
  {
    id: 3,
    title: "MacBook Pro 16-inch",
    price: 35000,
    discount: 2.5,
    prevPrice: 35900,
    imageUrl: "./images/seth-schwiet-WB3ujiKLJwQ-unsplash.jpg",
    category: "Electronics",
    stars: 4.3,
  },
  {
    id: 4,
    title: "Sony WH-1000XM4",
    price: 2400,
    discount: 7.5,
    prevPrice: 2600,
    imageUrl: "./images/yura-fresh-n31x0hhnzOs-unsplash.jpg",
    category: "Electronics",
    stars: 2.3,
  },
  {
    id: 5,
    title: "Nike Air Max 270",
    price: 1200,
    discount: 10.0,
    prevPrice: 1300,
    imageUrl: "./images/rahul-chakraborty-xsGxhtAsfSA-unsplash.jpg",
    category: "Footwear",
    stars: 4.5,
  },
  {
    id: 6,
    title: "Adidas Ultraboost",
    price: 1400,
    discount: 8.0,
    prevPrice: 1520,
    imageUrl: "./images/priscilla-du-preez-tBypczR1CFI-unsplash.jpg",
    category: "Footwear",
    stars: 1.3,
  },
  {
    id: 7,
    title: "Puma Running Shoes",
    price: 1000,
    discount: 12.0,
    prevPrice: 1136,
    imageUrl: "./images/rahul-chakraborty-xsGxhtAsfSA-unsplash.jpg",
    category: "Footwear",
    stars: 5,
  },
  {
    id: 8,
    title: "Levi's 501 Original Jeans",
    price: 800,
    discount: 5.0,
    prevPrice: 850,
    imageUrl: "./images/nordwood-themes-EZSm8xRjnX0-unsplash.jpg",
    category: "Clothing",
    stars: 4.3,
  },
  {
    id: 9,
    title: "H&M Cotton Shirt",
    price: 600,
    discount: 15.0,
    prevPrice: 700,
    imageUrl: "./images/kari-shea-1SAnrIxw5OY-unsplash.jpg",
    category: "Clothing",
    stars: 2.3,
  },
  {
    id: 10,
    title: "Zara Jacket",
    price: 1500,
    discount: 10.0,
    prevPrice: 1666,
    imageUrl: "./images/frank-park-nXruwpNrOzQ-unsplash.jpg",
    category: "Clothing",
    stars: 4.3,
  },
  {
    id: 11,
    title: "Apple Watch Series 7",
    price: 2500,
    discount: 4.0,
    prevPrice: 2600,
    imageUrl: "./images/crew-4Hg8LH9Hoxc-unsplash.jpg",
    category: "Accessories",
    stars: 1.3,
  },
  {
    id: 12,
    title: "Fitbit Charge 5",
    price: 1300,
    discount: 7.0,
    prevPrice: 1400,
    imageUrl: "./images/chris-lynch-KkTsH_vjjG8-unsplash.jpg",
    category: "Accessories",
    stars: 1.3,
  },
  {
    id: 13,
    title: "Ray-Ban Aviator Sunglasses",
    price: 1000,
    discount: 5.0,
    prevPrice: 1050,
    imageUrl: "./images/kari-shea-1SAnrIxw5OY-unsplash.jpg",
    category: "Accessories",
    stars: 1.3,
  },
  {
    id: 14,
    title: "KitchenAid Stand Mixer",
    price: 3000,
    discount: 6.0,
    prevPrice: 3190,
    imageUrl: "./images/bruno-van-der-kraan-VRERJ5Mjp4c-unsplash.jpg",
    category: "Home Appliances",
    stars: 2.3,
  },
  {
    id: 15,
    title: "Dyson V11 Vacuum Cleaner",
    price: 2800,
    discount: 4.5,
    prevPrice: 2930,
    imageUrl: "./images/caspar-camille-rubin-oI6zrBj3nKw-unsplash.jpg",
    category: "Home Appliances",
    stars: 2.4,
  },
  {
    id: 16,
    title: "Instant Pot Duo",
    price: 1200,
    discount: 8.5,
    prevPrice: 1311,
    imageUrl: "./images/bruno-van-der-kraan-VRERJ5Mjp4c-unsplash.jpg",
    category: "Home Appliances",
    stars: 4.2,
  },
  {
    id: 17,
    title: "Lego Star Wars Millennium Falcon",
    price: 5000,
    discount: 3.0,
    prevPrice: 5150,
    imageUrl: "./images/chris-lynch-KkTsH_vjjG8-unsplash.jpg",
    category: "Toys",
    stars: 3.3,
  },
  {
    id: 18,
    title: "Barbie Dreamhouse",
    price: 4000,
    discount: 5.0,
    prevPrice: 4200,
    imageUrl: "./images/crew-4Hg8LH9Hoxc-unsplash.jpg",
    category: "Toys",
    stars: 3.9,
  },
];

export default productsData;
